<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= $this->translate('Acl'); ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="list-group">
            <a href="<?= $this->url('admin/rumeaulibaclbackend-acl', ['controller' => 'roles']); ?>" class="list-group-item">
                <h4 class="list-group-item-heading"><?= $this->translate('Roles'); ?></h4>
                <p class="list-group-item-text"><?= $this->translate(
                        'Manage user roles, add or edit, nest roles, etc.'
                    ); ?></p>
            </a>

            <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading"><?= $this->translate('Resources'); ?></h4>
                <p class="list-group-item-text"><?= $this->translate(
                        'Manage your application resources.'
                    ); ?></p>
            </a>

            <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading"><?= $this->translate('Rules'); ?></h4>
                <p class="list-group-item-text"><?= $this->translate(
                        'Assing rules to each role, and allow or deny access to resources and fine tune your ACL.'
                    ); ?></p>
            </a>
        </div>
    </div>
</div>